In [1]:
print('hello')

hello


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [11]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c= np.array( [[[1,2,3],[4,5,6]],    [[1,2,3],[4,5,6]]] )
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [24]:
#ndim
a.ndim
b.ndim
c.ndim

# shape
print(a.shape)  
print(b.shape)  
print(c.shape)  


#dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)

(3,)
(2, 3)
(2, 2, 3)
int32
int32
int32


## arange

In [37]:
# range
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [38]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

## reshape

In [40]:
np.arange(1,101).reshape(2,10,5)

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

##  special matrix

In [43]:
np.zeros((2,3), dtype='bool')

array([[False, False, False],
       [False, False, False]])

In [45]:
np.ones((3,2), dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [83]:
## random
np.random.random(10)   #0-1

array([0.71294827, 0.25224163, 0.905342  , 0.9462043 , 0.90791855,
       0.16947568, 0.62378933, 0.57780151, 0.94228535, 0.3546097 ])

In [95]:
np.random.randint(10,15,3)

array([11, 13, 11])

In [111]:
a = np.random.random(2)
a

array([0.32986702, 0.01702057])

In [97]:
np.round(np.random.random(2))

array([0., 0.])

In [115]:
# floor and ceil
np.floor(2.0000001)

2.0

In [127]:
#   identity
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
#itemsiZe


a.itemsize

8

In [130]:
a = np.arange(10).reshape(2,5)
print(a)
print(a.itemsize)

[[0 1 2 3 4]
 [5 6 7 8 9]]
4
