## questions #chatgpt

Great! Here are some questions you can practice with:

What is the difference between min() and max() functions in NumPy?<br> <br>
How do you calculate the standard deviation of an array using NumPy?<br> <br>
What is the mean of an array in NumPy?<br> <br>
What does the shape attribute of an array represent in NumPy?<br> <br>
What does the ndim attribute of an array represent in NumPy?<br> <br>
How do you change the data type of an array using astype() function in NumPy?<br> <br>
How do you create an array of zeros or ones using NumPy?<br> <br>
How do you transpose a matrix using NumPy?<br> <br>
What are some random number generation functions available in NumPy?<br> <br>
How do you create an identity matrix using NumPy?<br> <br>
What is linspace() function used for in NumPy?<br> <br>
What is arange() function used for in NumPy?<br> <br>
What is itemsize attribute used for in NumPy?<br> <br>
How do you iterate over an array using nditer() function in NumPy?<br> <br>
How do you concatenate two arrays horizontally using hstack() function in NumPy?<br> <br>
How do you concatenate two arrays vertically using vstack() function in NumPy?<br> <br>
How do you split an array horizontally into multiple subarrays using hsplit() function in NumPy?<br> <br>
How do you split an array vertically into multiple subarrays using vsplit() function in NumPy?<br> <br>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [44]:
import numpy as np
#1d
np.array([1,2,3])

array([1, 2, 3])

In [45]:
# 2D
b = np.array([[1,2,3],[4,5,6],[2,3,4],[7,8,9]])
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [7 8 9]]
2
(4, 3)


In [46]:
#3d
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### dtype
- use1 --> dtype is used to get the data type of array
- use2--> also d type can be used as setting type of data while creating array
- <mark> while astype is used to covert datatype of array <mark>

In [6]:
# use1 - for getting data type of an array
x = np.array([1.2,3.2,4.1])
print(x)
print(x.dtype)

[1.2 3.2 4.1]
float64


In [7]:
#use2 -> setting type of an array while creation
a = np.array([1,2,3],dtype=float)
print(a)
print(a.dtype)

[1. 2. 3.]
float64


In [50]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [51]:
f

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [53]:
# np.ones and np.zeros
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## random fuctions 
</mark>  

`- random.randint(10,20) ` both inclusive  any random int also can create 2d arrays<br>
<br>
`- random.random((r,c))`  #r*c no of values between 0 and 1<br>
<br>
`- round(x) `    #round up kar dega x array ko to nearest

In [87]:
# getting random 1d array between -->
import random
a = np.random.randint(10,20,1)
print(a)
print(a.ndim)
print(type(a))

[15]
1
<class 'numpy.ndarray'>


In [91]:
# getting random 2d array between -->
a = np.random.randint(1,100,10).reshape(5,2)
print(a)
print(a.ndim)
print(type(a))

[[28 63]
 [32 80]
 [75 31]
 [98 52]
 [53 38]]
2
<class 'numpy.ndarray'>


In [74]:
# np.random -->(only gives numbers between 0 and 1 of given shape)
np.random.random((3,4))

array([[0.11227222, 0.13854746, 0.76444683, 0.62490044],
       [0.46867922, 0.03815835, 0.34103622, 0.48296171],
       [0.36109691, 0.68746758, 0.95361312, 0.25562117]])

In [75]:
# Round an array of numbers to the nearest integer
x = np.array([1.5, 2.3, 3.7, 4.9])
x_rounded = np.round(x)
print(x_rounded)


[2. 2. 4. 5.]


In [57]:
x = np.array([1,2.3,5.9])
np.round(x)


array([1., 2., 6.])

In [58]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

# np.linspace(5,10,3)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [59]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [61]:
a1 = np.arange(10,dtype=np.int32)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a2 = np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [63]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
# ndim
a3.ndim

3

In [65]:
a1 = np.array([[[1,2,3]]])
print(a1)
print(a1.ndim)
print(a1.shape)

[[[1 2 3]]]
3
(1, 1, 3)


In [68]:
# size
print(a2)
a2.size


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


12

In [70]:
a1 = np.array([[[1,2,3]]])
print(a1)
print(a1.size)

[[[1 2 3]]]
3


In [71]:
# itemsize
a = np.arange(10).reshape(2,5)
print(a)
print(a.itemsize)

[[0 1 2 3 4]
 [5 6 7 8 9]]
4


In [74]:
b = np.arange(10,dtype=float).reshape(2,5)
print(b)
print(b.itemsize)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
8


In [79]:
# dtype
print(a2)
print(a2.dtype)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
float64


In [80]:
print(a3)
print(a3.dtype)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int32


In [81]:
a4 = np.arange(12,dtype=float).reshape(3,4)
print(a4)
print(a4.dtype)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
float64


### Changing Datatype
`astype`

##  Note
<mark> 
- agar hum float size ya int size  (32 or 64) lete hai to 8 ke multiplication me itemsize deta hai<br>
- agar ham data type 64 lenge to itemsize 8 milega <br>
- agar ham data type 32 lenge to itemsize 4 milega </mark>

In [82]:
# astype
a3 = np.arange(10).reshape(2,5)
print(a3)
print(a3.dtype)
print(a3.itemsize)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
4


In [83]:
a3 = a3.astype(np.float64)
print(a3.dtype)
print(a3.itemsize)

float64
8


In [84]:
a3 = a3.astype(np.int64)
print(a3.dtype)
print(a3.itemsize)

int64
8


In [85]:
a3 = a3.astype(np.float32)
print(a3.dtype)
print(a3.itemsize)

float32
4


_____

### Array Operations

In [88]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### scalar operations

In [90]:
# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [91]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### vector operations

In [92]:
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

### Array Functions

In [108]:
# max/min/sum/prod
# 0 -> col and 1 -> row

np.prod(a1)

0

In [109]:
np.prod(a1,axis=0)          

array([3, 0])

In [110]:
np.prod(a1,axis=1) 

array([2, 3, 0])

In [111]:
# mean/median/std/var

np.var(a1,axis=1)
np.std(a1,axis=1)
np.std(a1,axis=0)


array([0.94280904, 0.81649658])

In [112]:
# trigonomoetric functions
np.sin(a1)

array([[0.84147098, 0.90929743],
       [0.14112001, 0.84147098],
       [0.84147098, 0.        ]])

In [114]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [115]:
# log and exponents
np.exp(a1)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692,  2.71828183],
       [ 2.71828183,  1.        ]])

### #round/floor/ceil
- ceil - round to higher
- florr - round to lowest
- round to nearest value


In [121]:
a = np.random.random((2,3))*100
a

array([[91.09838059,  0.45282387, 22.75215373],
       [80.12686304, 32.7890234 , 63.67241661]])

In [122]:
np.ceil(a)

array([[92.,  1., 23.],
       [81., 33., 64.]])

In [123]:
np.floor(a)

array([[91.,  0., 22.],
       [80., 32., 63.]])

In [124]:
np.round(a)

array([[91.,  0., 23.],
       [80., 33., 64.]])

_____

### Indexing and Slicing

In [125]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [128]:
#accessing 4 in a2
a2[1,0]

4

In [130]:
#accessing 5 in a3
print(a3)
a3[1,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


5

In [132]:
#accessng 6 in a3
a3[1,1,0]

6

### slicing

In [133]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [134]:
a1[2:5:2]

array([2, 4])

In [135]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [136]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [137]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [138]:
a2[1,::3]

array([4, 7])

In [139]:
print(a2)
a2[0,:]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [140]:
a2[:,2]

array([ 2,  6, 10])

In [141]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [142]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [143]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [144]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [145]:
a3[0,1,:]

array([3, 4, 5])

____

### Iterating

In [146]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [148]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [150]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [151]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [152]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [153]:
# reshape

In [155]:
# Transpose
print(a2)
np.transpose(a2)
a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [156]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [157]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [2]:
import numpy as np

In [3]:
# horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print("--------------------")
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [162]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [163]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [168]:
np.hsplit(a4,5)   # not possible 

ValueError: array split does not result in an equal division

In [169]:
np.hsplit(a4,3)         # ValueError: array split does not result in an equal division

ValueError: array split does not result in an equal division

In [171]:
np.hsplit(a4,2)     

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [172]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [173]:
np.vsplit(a5,2)    #ValueError: array split does not result in an equal division

ValueError: array split does not result in an equal division

In [174]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [175]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]